kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ include "enmasse.fullname" . }}-operator
  labels:
{{ include "enmasse.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.operator.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "enmasse.fullname" . }}-operator
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:        
        app.kubernetes.io/name: {{ include "enmasse.fullname" . }}-operator
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                  - key: node-role.enmasse.io/operator-infra
                    operator: In
                    values:
                      - "true"
      serviceAccountName: {{ include "enmasse.fullname" . }}-operator
      containers:
      - name: controller
        image: quay.io/enmasse/controller-manager:0.30.1
        imagePullPolicy: IfNotPresent
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: OPERATOR_NAME
          value: "enmasse-operator"
        - name: IMAGE_PULL_POLICY
          value: "IfNotPresent"
        - name: CONTROLLER_DISABLE_ALL
          value: "true"
        - name: CONTROLLER_ENABLE_IOT_CONFIG
          value: "true"
        - name: CONTROLLER_ENABLE_AUTHENTICATION_SERVICE
          value: "true"
        - name: CONTROLLER_MANAGER_IMAGE
          value: quay.io/enmasse/controller-manager:0.30.1
        - name: IOT_AUTH_SERVICE_IMAGE
          value: quay.io/enmasse/iot-auth-service:0.30.1
        - name: IOT_DEVICE_REGISTRY_FILE_IMAGE
          value: quay.io/enmasse/iot-device-registry-file:0.30.1
        - name: IOT_DEVICE_REGISTRY_INFINISPAN_IMAGE
          value: quay.io/enmasse/iot-device-registry-infinispan:0.30.1
        - name: IOT_GC_IMAGE
          value: 
        - name: IOT_HTTP_ADAPTER_IMAGE
          value: quay.io/enmasse/iot-http-adapter:0.30.1
        - name: IOT_MQTT_ADAPTER_IMAGE
          value: quay.io/enmasse/iot-mqtt-adapter:0.30.1
        - name: IOT_LORAWAN_ADAPTER_IMAGE
          value: quay.io/enmasse/iot-lorawan-adapter:0.30.1
        - name: IOT_SIGFOX_ADAPTER_IMAGE
          value: quay.io/enmasse/iot-sigfox-adapter:0.30.1
        - name: IOT_TENANT_SERVICE_IMAGE
          value: quay.io/enmasse/iot-tenant-service:0.30.1
        - name: IOT_PROXY_CONFIGURATOR_IMAGE
          value: quay.io/enmasse/iot-proxy-configurator:0.30.1
        - name: ROUTER_IMAGE
          value: quay.io/interconnectedcloud/qdrouterd:1.9.0
        - name: NONE_AUTHSERVICE_IMAGE
          value: quay.io/enmasse/none-authservice:0.30.1
        - name: KEYCLOAK_IMAGE
          value: quay.io/enmasse/keycloak-openshift:4.8.3.Final
        - name: KEYCLOAK_PLUGIN_IMAGE
          value: quay.io/enmasse/keycloak-plugin:0.30.1
        - name: CONTROLLER_ENABLE_CONSOLE_SERVICE
          value: "true"
        - name: CONSOLE_INIT_IMAGE
          value: "quay.io/enmasse/console-init:0.30.1"
        - name: CONSOLE_PROXY_OPENSHIFT_IMAGE
          value: "openshift/oauth-proxy:latest"
        - name: CONSOLE_PROXY_KUBERNETES_IMAGE
          value: "quay.io/pusher/oauth2_proxy:latest"
        - name: CONSOLE_HTTPD_IMAGE
          value: "quay.io/enmasse/console-httpd:0.30.1"
