apiVersion: v1
kind: Service
metadata:
  name: {{ include "enmasse.fullname" . }}-address-space-controller
  labels:
{{ include "enmasse.labels" . | indent 4 }}
spec:
  ports:
  - name: health
    port: 8080
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/name: {{ include "enmasse.fullname" . }}-address-space-controller
    app.kubernetes.io/instance: {{ .Release.Name }}
  type: ClusterIP
